name: Cypress Tests
on: [push]
jobs:
 Youtrainers-Test-with-Cypress:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v3
 
     - name: Run Cypress Test On Chrome
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome