name: Cypress Tests
on: [push]
jobs:
 Youtrainers-Test-with-Cypress:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run Cypress Test On Chrome
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome

     - name: Load test report history
       uses: actions/checkout@v3
       if: always()
       continue-on-error: true
       with:
         ref: gh-pages
         path: gh-pages

     - name: Build test report
       uses: simple-elf/allure-report-action@v1.7
       if: always()
       id: allure-report
       with:
         gh_pages: gh-pages
         allure_report: allure-report
         allure_history: allure-history
         allure_results: build/allure-results

     - name: Publish test report
       uses: peaceiris/actions-gh-pages@v3
       if: always()
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_branch: main
         publish_dir: allure-history